### ISSUE TITLE
uptime issue

### ISSUE THREAD

**Issue by githubertus** [dotgit/monitask#1]
running on a just rebooted Ubuntu 18.04, the uptime command gives
`10:24:11 up 1 min,  1 user,  load average: 0.48, 0.24, 0.09`
a little more than an hour later it gives
`11:43:13 up  1:20,  1 user,  load average: 0.00, 0.00, 0.00`
thus instead of an integer, I'm getting lines with hour:minutes like
`S_uptime_days,"by day",1603131120,1603130339,1728,"18:56,",0,1603131015,50,"19:07,",0,1728,"18:56,",0,270,"19:07,",1,94,1,5`
and maths like `$value_inc = $value - $bin[self::BIN_LAST_VALUE];` in store.php
are resulting in a lot of  `PHP Notice:  A non well formed numeric value encountered ` messages

**Comment by dotgit** [comment]
yeah. looks like it must take at least 24 hours to start displaying the uptime output as follows:
` 12:56:01 up 714 days, 11:59,  1 user,  load average: 0.05, 0.06, 0.00`
(we take 3rd parameter into account without parsing the 4th one...)
to be fixed

**Comment by dotgit** [comment]
@githubertus you can pull the new version with fix

**Comment by githubertus** [comment]
oops ... such a fast fix :)
in the meantime I was just trying ...
`sys.uptime = "uptime | awk -F'( |,|:)+' '{d=0; if ($7~/^day/) {d=$6}} {print \"S_uptime_days\", d+0}'"`

thanks a lot. great program.
