### ISSUE TITLE
positive/negative data strangeness

### ISSUE THREAD

**Issue by githubertus** [dotgit/monitask#2]
Hello again,
having run monitask for a week now besides several really nice and meaningful graphs I got a lot of others that appear a litte strange to me like this one:
![monitask](https://user-images.githubusercontent.com/9904364/97185398-4719a000-17a0-11eb-9b7f-9f2b3cd0573c.jpg)
On start, the red writes appear correctly acccording to the legend as negative.
Then I did a reboot, and things appear reversed and after another reboot, the data appears reversed again.
I'm wondering whether it is really meant that way?

**Comment by dotgit** [comment]
yeah, some counters are monotonously incrementing on each reboot (like for example `uptime`). when resetting this counter to 0 the system may get an overflow when subtracting previous value from the new one. this overflow is represented on your attached snapshot.
